module.exports = listOfBannedWords = [
  'top-hits',
  'traduccion-al',
  'traducao',
  'turkce-ceviri',
  'ubersetzungen',
  'traduction-francaise',
  'nederlandse-vertaling',
  'deutsche-ubersetzung',
  'russian-translations',
  'annotated',
  'english-translation',
  'genius-users',
  'summer-playlist',
  'tracklist',
  'spotify',
]
